# Generated by Django 4.1 on 2023-04-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_website_project_demo_slug_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
